Sanergy/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic import TemplateView
from users import views


from employee import urls
from users import views as user_views

urlpatterns = [
    path('', views.home, name='login'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('leave/', include('leave_management.urls')),
    path('employee/', include('employee.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name='login'),
    path('', views.password_reset_done, name="Reset_done"),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leave_management/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.leave_entitlement_types, name='leave_entitlement_types'),
    path('leave_application', views.leave_application, name='leave_application'),
    path('accruals', views.populate_leaveAccruals, name='accruals_leave'),
    path('leave_entitlement_types', views.leave_entitlement_types, name='leave_entitlement_types'),
    path('populate_employee_leave_request', views.populate_employee_leave_request, name='populate_employee_leave_request'),
    path('populate_sanergy_calender', views.populate_sanergy_calender, name='populate_sanergy_calender'),
    path('refresh_sanergy_calender', views.refresh_sanergy_calender, name='refresh_sanergy_calender'),
    path('post_leave_to_salesforce', views.post_leave_to_salesforce, name='post_leave_to_salesforce'),
    path('request_leave', views.request_leave, name='request_leave'),
    path('leave_page', views.request_leave_page, name='leave_page'),
    path('request_leave_data', views.request_leave_data, name='request_leave_data'),
    path('entitlement', views.entitlement_utilization, name='entitlement'),
    path('individual_leave_history', views.individual_leave_history, name='individual_leave_history'),
    path('sanergy_department_unit', views.sanergy_department_unit, name='sanergy_department_unit'),
    path('sanergy_department', views.sanergy_department, name='sanergy_department'),

]

users/urls.py
from django.urls import path
from . import views
# from ..leave_management.views import request_leave
from django.views.generic.base import TemplateView
from . import views


urlpatterns = [
    path('', views.landing, name='landing'),
    path('reset/done/', views.password_reset_done, name='password_reset_done'),
    path('create_custom_user/', views.create_custom_user, name='create_custom_user'),
    path('user_directory/', views.user_directory, name='user_directory'),
    # path('leave_page', views.request_leave, name='leave_page'),
]

leave_management/models.py
from django.db import models
from employee.models import  Employee


class Leave_Entitlement_Type(models.Model):
    Id = models.CharField(primary_key=True, max_length=50)
    Name = models.CharField(max_length=50, blank=False)
    Leave_Type = models.CharField(max_length=50, blank=False)
    Leave_Group = models.CharField(max_length=50, blank=False)


class LeaveAccruals(models.Model):
    Days_Accrued = models.CharField(max_length=100, blank=False)
    Days_Worked = models.CharField(max_length=100, blank=False, null=True )
    Employee = models.CharField(max_length=100, blank=True)
    Leave_Entitlement_Utilization = models.CharField(max_length=100, blank=True)
    Period = models.CharField(max_length=100, blank=False, null=True )


class EmployeeLeaveRequest(models.Model):
    Id = models.CharField(primary_key=True, max_length=400)
    approval_status = models.CharField(max_length=400, blank=False, null=True)
    comments = models.CharField(max_length=400, blank=False, null=True)
    coverage_plans = models.ForeignKey(Employee, on_delete=models.SET_NULL, blank=False, null=True, related_name='coverage_plans')
    department_team_lead = models.CharField(max_length=400, blank=False, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True)
    employee_s_department = models.CharField(max_length=400, blank=False, null=True)
    HR_approve_cancellation = models.BooleanField(max_length=400, blank=False, null=True)
    leave_approved = models.CharField(max_length=400, blank=False, null=True)
    leave_end_date = models.CharField(max_length=400, blank=False, null=True)
    leave_entitlement_utilization = models.CharField(max_length=400, blank=False, null=True)
    leave_start_date = models.CharField(max_length=400, blank=False, null=True)
    leave_started = models.CharField(max_length=400, blank=False, null=True)
    leave_type = models.CharField(max_length=400, blank=False, null=True)
    line_manager_account = models.ForeignKey(Employee, on_delete=models.SET_NULL, blank=False, null=True, related_name='line_manager_account')
    line_manager_approve_cancellation = models.CharField(max_length=400, blank=False, null=True)
    next_step = models.CharField(max_length=400, blank=False, null=True)
    next_step_due_date = models.CharField(max_length=400, blank=False, null=True)
    no_of_approved_leave_days = models.CharField(max_length=400, blank=False, null=True)
    no_of_leave_days_requested = models.CharField(max_length=400, blank=False, null=True)
    request_from_VFP = models.CharField(max_length=400, blank=False, null=True)
    sick_leave_doc_attached = models.FileField(upload_to='sick_leave_documents', null=True, blank=False)
    stage = models.CharField(max_length=400, blank=False, null=False, default='Open')
    startEndDate = models.CharField(max_length=400, blank=False, null=True)

    def __str__(self):
        return '%s %s %s' % (self.Id, self.employee, self.leave_type)


class SanergyCalendar(models.Model):
    Date = models.CharField(max_length=100, null=True, blank=True)
    Decsritption = models.CharField(max_length=300, null=True, blank=True)
    isBusinessDay = models.BooleanField(null=True, blank=True)
    isBusinessDayInclSat = models.BooleanField(null=True, blank=True)
    isHoliday = models.BooleanField(null=True, blank=True)
    isWeekend = models.BooleanField(null=True, blank=True)
    isWeekend_or_Holiday = models.BooleanField(null=True, blank=True)
    Weekday_Name = models.CharField(max_length=100, null=True, blank=True)
    Weekday_No = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.Decsritption


class Leave_Entitlement_Utilization(models .Model):
    id = models.CharField(primary_key=True, max_length=400)
    Accrued_To_Date_Selected = models.CharField(max_length=300, null=True, blank=True)
    Employee = models.CharField(max_length=300, null=True, blank=True)
    Leave_Days_Accrued = models.CharField(max_length=300, null=True, blank=True)
    Leave_Days_Remaining = models.CharField(max_length=300, null=True, blank=True)
    Leave_Days_Scheduled = models.CharField(max_length=300, null=True, blank=True)
    Leave_Days_Used = models.CharField(max_length=300, null=True, blank=True)
    Leave_Entitlement_Type_Config = models.CharField(max_length=300, null=True, blank=True)
    Leave_Type = models.CharField(max_length=300, null=True, blank=True)
    Leave_Type_Name = models.CharField(max_length=300, null=True, blank=True)
    Leave_Year = models.CharField(max_length=300, null=True, blank=True)
    Total_No_of_Leave_Days = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.Leave_Days_Accrued


class SanergyDepartment(models.Model):
    id = models.CharField(primary_key=True, max_length=400)
    name = models.CharField(max_length = 100, blank=True, null=True)
    approver = models.CharField(max_length=300, null=True, blank=True)
    company = models.CharField(max_length=300, null=True, blank=True)
    department_code = models.CharField(max_length=300, null=True, blank=True)
    department_status = models.CharField(max_length=300, null=True, blank=True)
    team_lead = models.CharField(max_length = 1000, null=True, blank=True)
    team_lead_sf_account = models.CharField(max_length = 1000, null=True, blank=True)

    def __str__(self):
        return self.department_code


class SanergyDepartmentUnit(models.Model):
    id = models.CharField(primary_key=True, max_length=400)
    name = models.CharField(max_length = 100, blank=True, null=True)
    active = models.BooleanField(null=True, blank=True)
    approver = models.CharField(max_length=300, null=True, blank=True)
    department_unit_code = models.CharField(max_length = 100, null=True, blank=True)
    line_manager = models.CharField(max_length=100, null=True, blank=True)
    line_manager_sf_account = models.CharField(max_length=100, null=True, blank=True)
    sanergy_department = models.ForeignKey(SanergyDepartment, on_delete=models.SET_NULL, null=True, blank=True)
    talent_partner_emp_eccount = models.CharField(max_length=100, null=True, blank=True)
    talent_partner = models.CharField(max_length=100, null=True, blank=True)
    team_lead = models.CharField(max_length = 1000, null=True, blank=True)
    team_lead_sf_account = models.CharField(max_length = 1000, null=True, blank=True)
    uit_code = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.department_unit_code

    @classmethod
    def fetch_department_units(cls):
        all_department_units = cls.objects.all()
        return all_department_units.department_unit_code

leave_management/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import transaction
from .models import EmployeeLeaveRequest, Leave_Entitlement_Type

leave_choices = [
    
    ('annual leave','Annual leave'),
    ('compassion leave','Compassion leave'),
    ('maternity leave','Maternity leave'),
    ('Paternity leave', 'Paternity leave'),
    ('study leave', 'Study leave'),
  ]

class LeaveApplicationForm(forms.ModelForm):

    class Meta:
        model= EmployeeLeaveRequest
        widgets = {
           'leave_start_date':forms.DateTimeInput(attrs={ 'class':
               'datetime-input'}),
            'leave_end_date':forms.DateTimeInput(attrs={ 'class':
               'datetime-input'}),
            'Leave_Type':forms.Select(choices=leave_choices)
        }

        fields=['leave_type','leave_start_date','leave_end_date','coverage_plans',]

leave_management/templates/leave_templates/base.html
{% load bootstrap4 %}
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      
    {% if title %}
    <title>Leave Management System - {{title}}</title>
    {% else %}
        <title> Leave Management System </title>
    {% endif %}
      
    {% block styles %}

    <link rel="stylesheet" type="text/css" href="css/jquery.countdown.css"> 
    <script type="text/javascript" src="js/jquery.countdown.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    
    {% bootstrap_css %}
    {% endblock %}

</head>

<body>
    {% block content %}
        {% include 'leave_templates/messaging.html' %}

    {% endblock %}
    {% block scripts %}

    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css"
        rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

    {% bootstrap_javascript %}
    {% endblock %}

</body>
</html>

leave_management/templates/leave_templates/leave_application.html
{% extends "leave_templates/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Apply leave</title>
    {{form.media}}

    {% block styles %} {% bootstrap_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    {% endblock %}

</head>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        border-radius: 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
    #id_Leave_Type{
       
        height: 50px;
        border-radius: 25px;
        text-align: center;
    }
    #id_Begin_Date{
       
       height: 50px;
       border-radius: 25px;
   }
   #id_End_Date{
       
       height: 50px;
       border-radius: 25px;
   }
   #id_Requested_Days{
       
       height: 50px;
       border-radius: 25px;
   }
    #id_Comments{
        height: 100px;
        border-radius: 25px;
    }
</style>

<body class="container-fluid">
    <!-- flash messages cong  -->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <!-- flash messages cong  -->
    {% include 'leave_templates/navbar.html' %}
    <div class="panel panel-default">
        <div class="row">
            <div class="col-6" style="padding-right: 200px; padding-left:30px; margin-top: 100px;">
                <div class="card"
                    style="width: 400px; box-shadow: 0 40px 15px 0 rgba(0, 0, 0, 0.2); height: 500px; font-weight: 600; ">
                    <div class="card-body" style="padding-top: 90px;">
                        <form action="{% url 'leave_application'%}" method="post" enctype="multipart/form-data"
                            style="height: 50px;">

                            {% csrf_token%}
                            {% bootstrap_form leaveform %}


                            <div class="form-group text-center">
                                <input type="submit" class="btn btn-primary sign-up-button" value="Apply">
                            </div>
                            <input type="hidden" name="next" value="">
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-6 " style="padding-top: 100px; padding-right: 40px; ">
                <table>
                    <tr>
                        <th>Employee </th>
                        <th>Type</th>
                      
                        <th>Begin Date</th>
                        <th>End Date</th>
                        <th>Requested Days</th>
                        <th>Status </th>
                      
                        <!-- <th> Leave Type</th> -->

                    </tr>
                    {% for leave in leavess %}
                    <tr>

                        <td>{{leave.user.username}}</td>
                        <td>{{leave.Leave_Type}}</td>
                       
                        <td>{{leave.Begin_Date}}</td>
                        <td>{{leave.End_Date}}</td>
                        <td>{{leave.Requested_Days}}</td>
                        <td>{{leave.get_leave_status_display}}</td>

                    </tr>
                    {% endfor%}
                </table>

            </div>
        </div>
    </div>



    {% block scripts %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css"
        rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
    
    <script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format: 'YYYY-MM-DD'
            });
        });
    </script>
    {% bootstrap_javascript %}
    {% endblock %}

</body>

</html>
{% endblock %}

leave_management/templates/leave_templates/messaging.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

leave_management/templates/leave_templates/navbar.html
<html>
    <head>
    <style>
    #ul-nav {
      list-style-type: none;
      margin: 0;
      padding: 0;
      color: #035385;
      overflow: hidden;
      background-color: #EDDD30;
       position: fixed;
       width:100%;
    }
    ​
    .list {
      float: left;
    }
    ​
    li a {
      display: block;
      font-size: 20px;
    ​  color: #035385;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }
    ​
    ​
    ​
    .active {
      background-color: #EDDD30;
    }
    </style>
    ​
    </head>
    <body>
    ​
    <ul id="ul-nav" >
    ​
      <li class="list"><a href="homepage.html" class="link"><img class="nav-logo" src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-white-195.png" width="160px" alt="Sanergy" style="height: 60px;"></a></li>
      <li class="list" style="float:right" class="link"><a class="active" href="#history" style="color: #035385;padding-top: 34px;">History</a></li>
      <li class="list" style="float:right" class="link"><a class="active" href="#balance" style="color: #035385;padding-top: 34px;">Balance</a></li>
      <li class="list" style="float:right" class="link"><a class="active" href="#opening" style="color: #035385;padding-top: 34px;">Form</a></li>
    ​
    </ul>
    ​
    </body>
    </html>